require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

# Disable cops that cause internal errors with rubocop-rspec 2.31
FactoryBot/AssociationStyle:
  Enabled: false

FactoryBot/ExcessiveCreateList:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false

# Relaxed rules for portfolio project
Metrics/MethodLength:
  Max: 55

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 45

Metrics/ClassLength:
  Max: 200

Metrics/ParameterLists:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Lint cops - allow unused args for GraphQL method signatures
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/UnusedBlockArgument:
  AllowUnusedKeywordArguments: true

Lint/MissingSuper:
  Enabled: false

Lint/RedundantSafeNavigation:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

# Rails cops
Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/Exit:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/DangerousColumnNames:
  Enabled: false

Rails/TransactionExitStatement:
  Enabled: false

Rails/FindByOrAssignmentMemoization:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/Blank:
  Enabled: false

Rails/WhereRange:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/RootPathnameMethods:
  Enabled: false

# RSpec cops - relaxed for readability
RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/DescribeClass:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

# Naming
Naming/MethodParameterName:
  AllowedNames:
    - e
    - id
    - _

Naming/BlockForwarding:
  Enabled: false

# Layout
Layout/LineLength:
  Max: 150

# Bundler
Bundler/OrderedGems:
  Enabled: false

# Style
Style/SafeNavigationChainLength:
  Enabled: false
